variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  
stages:
  - build
  
build-phase:
  image: node:14.18.1
  stage: build
  tags:
    - pms
  before_script:
    - rm -rf ./node_modules ./yarn.lock ./package-lock.json
    - npm install node-sass/^7.0.1 --force
    - npm install --save --legacy-peer-deps
    - id
    - pwd
    - ls
  script:
    - echo "run build"
    - npm run prod
  after_script:
    - pwd
