variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  
stages:
  - build
 
build-phase:      
  stage: build
  tags:
    - pms
  before_script:
    - id
    - pwd
    - ls
  script:
    - echo "run build"
  after_script:
    - pwd
    - ls
    - vue-cli-service build --mode prod