image: gradle:alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  
stages:
 - build
 - test
before_script:
  - pwd
  - ls

build:
  stage: build
  script: 
   - echo "run build"
   - npm run prod

test:
  stage: test
  script: gradle check
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    policy: pull
    paths:
      - build
      - .gradle


