image: gradle:alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  
stages:
 - build
 - test

build:
  stage: build
  script: 
   - echo "Build Start"
   - gradle --build-cache assemble
   - echo "run build"
   - npm run build
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - build
      - .gradle

test:
  stage: test
  script: gradle check
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    policy: pull
    paths:
      - build
      - .gradle
