variables:
  SONAR_OPTS: "-Dsonar.host.url=https://sonar.iteyes-lab.gurmwi.io -Dsonar.login=$SONAR_TOKEN -Dsonar.gitlab.project_id=$CI_PROJECT_PATH -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.gitlab.query_max_retry=50 -Dsonar.gitlab.query_wait=5000"
  GIT_STRATEGY: clone

cache:
  paths:
    - ./node_modules/
    - build
  key: $CI_COMMIT_REF_SLUG

stages:
  - build
  - verify
  - publish

before_script:
  - npm cache clean --force
  - npm install @vue/cli
  - yarn

sonarqube_master:
  stage: verify
  script:
    - sonar-scanner $SONAR_OPTS
  only:
    - master

build.npm:
  stage: build
  script:
    - echo "Build Start"
    - npm run build
    - pwd

publish.npm:
  stage: publish
  dependencies:
    - build.npm
  only:
    - master
  script:
    - npm publish
