variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
cache:
  paths:
    - ./node_modules/
  key: $CI_COMMIT_REF_SLUG
  
stages:
  - build
 
build-phase:      
  stage: build
  tags:
    - pms
  before_script:
    - npm cache clean --force
    - id
    - pwd
    - ls
    - npm --version
    - npm show node-sass version
    - npm install
    - yarn add -D node-sass/^6.0.1
  script:
    - echo "run build"
    - npm run prod
    
    
  after_script:
    - pwd
    