variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  
stages:
 - build
 
build-phase:      
  stage: build
  tags:
   - pms
  before_script:
    - id
    - pwd
    - cd ../
    - cp -f pms-front/* /home/admin
  script:
    - echo "run build"
    - npm run build