variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  
stages:
  - build
  
build-pms:
  image: node:14.18.1
  stage: build
  tags:
    - pms
  before_script:
    - echo "before_script"
    - rm -rf ./node_modules ./yarn.lock ./package-lock.json
    - npm install --save --legacy-peer-deps
  script:
    - echo "run build"
    - npm run prod
  after_script:
    - echo "publish pms"
    - cd ../
    - sh publish.sh
    - sudo systemctl status nginx
    - sudo netstat -nltp
